const { db } = require('../config/firebase');

// Default settings seeded on first use
const DEFAULT_SETTINGS = {
  church_profile: {
    churchName: 'Grace Community Church',
    address: '123 Faith Avenue',
    phone: '',
    email: '',
    website: '',
    pastorName: '',
    tagline: 'Building Lives, Transforming Communities',
    mandate: '',
    vision: '',
    currency: 'USD',
    logoUrl: ''
  },
  financial: {
    tithePercentage: 10,
    decimalPrecision: 2,
    enableSummaryCards: true
  },
  attendance: {
    enableTracking: true,
    grouping: 'Per Service',
    autoWeeklyTotals: true,
    includeInReports: true,
    warningThreshold: 50
  },
  reports: {
    weekStartsOn: 'Sunday',
    autoGenerate: false,
    weekly: { income: true, expenses: true, attendance: true, perService: true },
    monthly: { summary: true, tithe: true, categories: true, attendance: true }
  },
  pdf_branding: {
    primaryColor: '#4f46e5',
    footerText: 'Generated by FaithFlow Church Management System',
    pageSize: 'A4',
    orientation: 'Portrait',
    includeTreasurerSignature: false,
    includePastorSignature: false
  },
  notifications: {
    weeklyReportEmail: false,
    monthlyReportEmail: false,
    noAttendanceReminder: true,
    noExpensesReminder: true,
    reportReadyNotification: true
  },
  system: {
    theme: 'Light',
    dateFormat: 'DD/MM/YYYY',
    paginationSize: 25
  }
};

const DEFAULT_SERVICES = [
  { id: 's1', name: 'Sunday 1st Service', type: 'Sunday', order: 1, active: true, trackAttendance: true, trackFinance: true },
  { id: 's2', name: 'Sunday 2nd Service', type: 'Sunday', order: 2, active: true, trackAttendance: true, trackFinance: true },
  { id: 's3', name: 'Midweek Service', type: 'Midweek', order: 3, active: true, trackAttendance: true, trackFinance: false }
];

const DEFAULT_INCOME_CATEGORIES = [
  { id: 'ic1', name: 'Offering', color: '#4f46e5', active: true },
  { id: 'ic2', name: 'Tithe', color: '#10b981', active: true },
  { id: 'ic3', name: 'Transferred Offering', color: '#f59e0b', active: true },
  { id: 'ic4', name: 'Covenant Seed', color: '#ef4444', active: true },
  { id: 'ic5', name: 'Project Seed', color: '#8b5cf6', active: true },
  { id: 'ic6', name: 'Altar Seed', color: '#06b6d4', active: true },
  { id: 'ic7', name: 'Special Seed', color: '#f97316', active: true },
  { id: 'ic8', name: 'Thanksgiving', color: '#84cc16', active: true },
  { id: 'ic9', name: 'Donation', color: '#ec4899', active: true }
];

const DEFAULT_EXPENSE_CATEGORIES = [
  { id: 'ec1', name: 'Fuel', color: '#f59e0b', active: true, budgetLimit: null },
  { id: 'ec2', name: 'Electricity', color: '#ef4444', active: true, budgetLimit: null },
  { id: 'ec3', name: 'Welfare', color: '#10b981', active: true, budgetLimit: null },
  { id: 'ec4', name: 'Sound Maintenance', color: '#8b5cf6', active: true, budgetLimit: null },
  { id: 'ec5', name: 'Building Project', color: '#f97316', active: true, budgetLimit: null },
  { id: 'ec6', name: 'Transport', color: '#06b6d4', active: true, budgetLimit: null },
  { id: 'ec7', name: 'Staff Support', color: '#4f46e5', active: true, budgetLimit: null },
  { id: 'ec8', name: 'Internet', color: '#84cc16', active: true, budgetLimit: null },
  { id: 'ec9', name: 'Media', color: '#ec4899', active: true, budgetLimit: null },
  { id: 'ec10', name: 'Cleaning', color: '#64748b', active: true, budgetLimit: null }
];

const getChurchId = (req) => {
  if (!req.user || !req.user.churchId) throw new Error('Unauthorized: No workspace assigned');
  return req.user.churchId;
};

// Helper to check and seed defaults
async function seedDefaultsIfNeeded(churchId) {
  const settingsRef = db.collection(`churches/${churchId}/settings`).doc('config');
  const settingsDoc = await settingsRef.get();
  
  if (!settingsDoc.exists) {
    await settingsRef.set(DEFAULT_SETTINGS);
  }

  // Check and seed services if empty
  const svcRef = db.collection(`churches/${churchId}/services`);
  const svcSnap = await svcRef.get();
  if (svcSnap.empty) {
    for (const svc of DEFAULT_SERVICES) {
      await svcRef.doc(svc.id).set(svc);
    }
  }

  // Check and seed income categories if empty
  const icRef = db.collection(`churches/${churchId}/income_categories`);
  const icSnap = await icRef.get();
  if (icSnap.empty) {
    for (const ic of DEFAULT_INCOME_CATEGORIES) {
      await icRef.doc(ic.id).set(ic);
    }
  }

  // Check and seed expense categories if empty
  const ecRef = db.collection(`churches/${churchId}/expense_categories`);
  const ecSnap = await ecRef.get();
  if (ecSnap.empty) {
    for (const ec of DEFAULT_EXPENSE_CATEGORIES) {
      await ecRef.doc(ec.id).set(ec);
    }
  }
}

// GET all settings
exports.getSettings = async (req, res) => {
  try {
    const churchId = getChurchId(req);
    await seedDefaultsIfNeeded(churchId);
    
    const settingsDoc = await db.collection(`churches/${churchId}/settings`).doc('config').get();
    
    const [servicesSnap, icSnap, ecSnap] = await Promise.all([
      db.collection(`churches/${churchId}/services`).get(),
      db.collection(`churches/${churchId}/income_categories`).get(),
      db.collection(`churches/${churchId}/expense_categories`).get()
    ]);
    
    res.json({
      settings: settingsDoc.exists ? { ...DEFAULT_SETTINGS, ...settingsDoc.data() } : DEFAULT_SETTINGS,
      services: servicesSnap.docs.map(d => ({ id: d.id, ...d.data() })),
      income_categories: icSnap.docs.map(d => ({ id: d.id, ...d.data() })),
      expense_categories: ecSnap.docs.map(d => ({ id: d.id, ...d.data() }))
    });
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: 'Failed to load settings' });
  }
};

// UPDATE a settings section (e.g. church_profile, financial, etc.)
exports.updateSettings = async (req, res) => {
  try {
    const churchId = getChurchId(req);
    const { section } = req.params;
    const updates = req.body;
    
    const settingsRef = db.collection(`churches/${churchId}/settings`).doc('config');
    const doc = await settingsRef.get();
    
    if (doc.exists) {
      const current = doc.data();
      current[section] = { ...(current[section] || {}), ...updates };
      await settingsRef.update(current);
      res.json({ message: 'Settings saved', settings: current[section] });
    } else {
      res.status(404).json({ error: 'Settings not found' });
    }
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: 'Failed to save settings' });
  }
};

// SERVICES
exports.listServices = async (req, res) => {
  try {
    const snap = await db.collection(`churches/${getChurchId(req)}/services`).get();
    res.json(snap.docs.map(d => ({ id: d.id, ...d.data() })));
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

exports.createService = async (req, res) => {
  try {
    const docRef = db.collection(`churches/${getChurchId(req)}/services`).doc();
    const item = { ...req.body, active: true };
    await docRef.set(item);
    res.status(201).json({ id: docRef.id, ...item });
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

exports.updateService = async (req, res) => {
  try {
    const { id } = req.params;
    await db.collection(`churches/${getChurchId(req)}/services`).doc(id).update(req.body);
    res.json({ message: 'Service updated' });
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

exports.deleteService = async (req, res) => {
  try {
    const { id } = req.params;
    await db.collection(`churches/${getChurchId(req)}/services`).doc(id).delete();
    res.json({ message: 'Service deleted' });
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

// INCOME CATEGORIES
exports.listIncomeCategories = async (req, res) => {
  try {
    const snap = await db.collection(`churches/${getChurchId(req)}/income_categories`).get();
    res.json(snap.docs.map(d => ({ id: d.id, ...d.data() })));
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

exports.createIncomeCategory = async (req, res) => {
  try {
    const docRef = db.collection(`churches/${getChurchId(req)}/income_categories`).doc();
    const item = { ...req.body, active: true };
    await docRef.set(item);
    res.status(201).json({ id: docRef.id, ...item });
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

exports.updateIncomeCategory = async (req, res) => {
  try {
    const { id } = req.params;
    await db.collection(`churches/${getChurchId(req)}/income_categories`).doc(id).update(req.body);
    res.json({ message: 'Category updated' });
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

exports.deleteIncomeCategory = async (req, res) => {
  try {
    const { id } = req.params;
    await db.collection(`churches/${getChurchId(req)}/income_categories`).doc(id).delete();
    res.json({ message: 'Category deleted' });
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

// EXPENSE CATEGORIES
exports.listExpenseCategories = async (req, res) => {
  try {
    const snap = await db.collection(`churches/${getChurchId(req)}/expense_categories`).get();
    res.json(snap.docs.map(d => ({ id: d.id, ...d.data() })));
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

exports.createExpenseCategory = async (req, res) => {
  try {
    const docRef = db.collection(`churches/${getChurchId(req)}/expense_categories`).doc();
    const item = { ...req.body, active: true };
    await docRef.set(item);
    res.status(201).json({ id: docRef.id, ...item });
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

exports.updateExpenseCategory = async (req, res) => {
  try {
    const { id } = req.params;
    await db.collection(`churches/${getChurchId(req)}/expense_categories`).doc(id).update(req.body);
    res.json({ message: 'Category updated' });
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

exports.deleteExpenseCategory = async (req, res) => {
  try {
    const { id } = req.params;
    await db.collection(`churches/${getChurchId(req)}/expense_categories`).doc(id).delete();
    res.json({ message: 'Category deleted' });
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

// EXPORT CSV
function toCSV(arr) {
  if (!arr.length) return '';
  const keys = Object.keys(arr[0]).filter(k => k !== 'id');
  const header = keys.join(',');
  const rows = arr.map(item => keys.map(k => `"${item[k] ?? ''}"`).join(','));
  return [header, ...rows].join('\n');
}

exports.exportCSV = async (req, res) => {
  try {
    const { collection } = req.params;
    const allowed = ['income', 'expenses', 'attendance', 'members'];
    if (!allowed.includes(collection)) return res.status(400).json({ error: 'Invalid collection' });
    
    // Using flat collection for legacy data or scoped by churchId?
    // We'll query flat 'income' for now as other controllers haven't been updated yet.
    const snap = await db.collection(collection).get();
    const data = snap.docs.map(d => ({ id: d.id, ...d.data() }));
    
    const csv = toCSV(data);
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="${collection}_export.csv"`);
    res.send(csv);
  } catch (e) { res.status(500).json({ error: 'Export failed' }); }
};

// LIST USERS
exports.listUsers = async (req, res) => {
  try {
    const snap = await db.collection('users').where('churchId', '==', getChurchId(req)).get();
    const users = snap.docs.map(d => ({ id: d.id, name: d.data().name, email: d.data().email, role: d.data().role, isVerified: d.data().isVerified }));
    res.json(users);
  } catch (e) { res.status(500).json({ error: 'Failed to list users' }); }
};

// CREATE USER
exports.createUser = async (req, res) => {
  try {
    const churchId = getChurchId(req);
    const { name, email, password, role } = req.body;
    
    if (!name || !email || !password) return res.status(400).json({ error: 'Missing fields' });
    
    // Check if email exists
    const existing = await db.collection('users').where('email', '==', email.toLowerCase()).get();
    if (!existing.empty) return res.status(400).json({ error: 'User with this email already exists' });
    
    const bcrypt = require('bcryptjs');
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);
    
    const docRef = await db.collection('users').add({
      name,
      email: email.toLowerCase(),
      password: hashedPassword,
      role: role || 'user',
      churchId,
      isVerified: true, // Auto-verified since admin created them
      created_at: new Date().toISOString()
    });
    
    res.status(201).json({ message: 'User created successfully', id: docRef.id });
  } catch (e) { 
    res.status(500).json({ error: 'Failed to create user' }); 
  }
};

exports.updateUserRole = async (req, res) => {
  try {
    const { id } = req.params;
    const { role } = req.body;
    await db.collection('users').doc(id).update({ role });
    res.json({ message: 'Role updated' });
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

exports.deleteUser = async (req, res) => {
  try {
    const { id } = req.params;
    const doc = await db.collection('users').doc(id).get();
    if (!doc.exists || doc.data().churchId !== getChurchId(req)) return res.status(403).json({ error: 'Unauthorized' });
    await db.collection('users').doc(id).delete();
    res.json({ message: 'User removed' });
  } catch (e) { res.status(500).json({ error: 'Failed' }); }
};

// LOGO UPLOAD
exports.uploadLogo = async (req, res) => {
  try {
    const { imageBase64 } = req.body;
    if (!imageBase64) return res.status(400).json({ error: 'No image provided' });
    
    const churchId = getChurchId(req);
    const fs = require('fs');
    const path = require('path');
    
    // Create public/logos directory if it doesn't exist
    const logosDir = path.join(__dirname, '../public/logos');
    if (!fs.existsSync(logosDir)) fs.mkdirSync(logosDir, { recursive: true });
    
    // Strip the base64 header (e.g. data:image/png;base64,)
    const base64Data = imageBase64.replace(/^data:image\/\w+;base64,/, "");
    const filename = `${churchId}_logo_${Date.now()}.png`;
    const filePath = path.join(logosDir, filename);
    
    fs.writeFileSync(filePath, base64Data, 'base64');
    
    const logoUrl = `/public/logos/${filename}`;
    
    // Update settings
    const settingsRef = db.collection(`churches/${churchId}/settings`).doc('config');
    const doc = await settingsRef.get();
    if (doc.exists) {
      const current = doc.data();
      current.church_profile = current.church_profile || {};
      current.church_profile.logoUrl = logoUrl;
      await settingsRef.update(current);
    }
    
    res.json({ message: 'Logo uploaded successfully', logoUrl });
  } catch (e) {
    console.error('Logo upload error:', e);
    res.status(500).json({ error: 'Failed to upload logo' });
  }
};

// BACKUP
exports.downloadBackup = async (req, res) => {
  try {
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Content-Disposition', `attachment; filename="faithflow_backup_${Date.now()}.json"`);
    res.send(JSON.stringify({ note: "Backup disabled pending full firestore migration" }, null, 2));
  } catch (e) { res.status(500).json({ error: 'Backup failed' }); }
};

exports.restoreBackup = async (req, res) => {
  res.status(500).json({ error: 'Restore disabled pending full firestore migration' });
};

